version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 👷

  # Update dev-dependencies
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
      timezone: Europe/Berlin
    commit-message:
      prefix: '⬆'
    ignore:
      - dependency-name: marshmallow
    versioning-strategy: increase
